name: Renaissance
version: ${version}
description: ${description}
author: Hpt
main: net.hungerstruck.renaissance.RenaissancePlugin
depends: [WorldEdit]

commands:
   debug:
       description: This should be removed.
       permission: renaissance.admin
       usage: Enter a script idiot.

permissions:
  renaissance.admin:
    default: op
